-- Run once as the database owner: psql -d module_4 -f db/schema.sql
CREATE TABLE IF NOT EXISTS applicants (
    p_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program TEXT,
    comments TEXT,
    date_added DATE,
    url TEXT,
    status TEXT,
    term TEXT,
    us_or_international TEXT,
    gpa FLOAT,
    gre FLOAT,
    gre_v FLOAT,
    gre_aw FLOAT,
    degree TEXT,
    llm_generated_program TEXT,
    llm_generated_university TEXT
);
